# Generated by Django 3.0.3 on 2020-03-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200306_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='watts_rating',
            field=models.IntegerField(default=0),
        ),
    ]
