# Generated by Django 3.0.4 on 2020-03-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_devices_watts_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField()),
                ('trigger_time', models.TimeField()),
                ('device_state', models.BooleanField(default=False)),
            ],
        ),
    ]
