# Generated by Django 3.0.4 on 2020-03-21 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_schedule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule',
            new_name='Schedules',
        ),
    ]
