# Generated by Django 3.0.4 on 2020-03-28 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20200321_2336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedules',
        ),
    ]
