# Generated by Django 3.0.3 on 2020-03-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200306_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logging',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
